services:
  redis-master:
    image: redis:6.0.7
    container_name: redis-master
    command: ["redis-server", "--maxmemory", "100mb", "--maxmemory-policy", "allkeys-lru"]
    restart: always
    volumes:
      - redis_master:/data
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}

  redis-replica:
    image: redis:6.0.7
    container_name: redis-replica
    restart: always
    volumes:
      - redis_replica:/data
    ports:
      - ${REDIS_REPLICA_PORT}:${REDIS_PORT}
    command: redis-server --replicaof redis-master ${REDIS_PORT}

volumes:
  redis_master:
  redis_replica: