services:
  redis-master:
    image: redis:6.0.7
    container_name: redis-master
    restart: always
    volumes:
      - redis_master:/data
    ports:
      - 6379:6379

  redis-replica:
    image: redis:6.0.7
    container_name: redis-replica
    restart: always
    volumes:
      - redis_replica:/data
    ports:
      - 6479:6379
    command: redis-server --replicaof redis-master 6379

volumes:
  redis_master:
  redis_replica: